/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.intelbras.view;

import br.com.intelbras.controler.InicioControler;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class InicioView extends javax.swing.JFrame {

    InicioControler inicioControler;
    HashMap<String, Object> mapaComponentes;
    /**
     * Creates new form InicioView
     */
    public InicioView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.inseriMapa();
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int lar = (int) d.getWidth();
        int alt = (int) d.getHeight();
        
        this.setSize(d);
        this.lbl_fundo.setSize(d);
        this.inicioControler = new InicioControler(mapaComponentes);
        this.inicioControler.setPosicao();

        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btn_historico = new javax.swing.JButton();
        btn_pontos = new javax.swing.JButton();
        btn_vendas = new javax.swing.JButton();
        btn_funcionario = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_produto = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        lbl_fundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnu_cliente = new javax.swing.JMenu();
        mnu_funcionario = new javax.swing.JMenu();
        mnu_vendas = new javax.swing.JMenu();
        mnu_pontos = new javax.swing.JMenu();
        mnu_produto = new javax.swing.JMenu();
        mnu_login = new javax.swing.JMenu();
        mnu_alterarFundo = new javax.swing.JMenu();
        mnu_logout = new javax.swing.JMenu();
        mnu_sair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btn_historico.setText("Histórico");
        btn_historico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_historicoMouseDragged(evt);
            }
        });
        btn_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_historicoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_historicoMouseReleased(evt);
            }
        });
        getContentPane().add(btn_historico);
        btn_historico.setBounds(140, 180, 110, 70);

        btn_pontos.setText("Pontos");
        btn_pontos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_pontosMouseDragged(evt);
            }
        });
        btn_pontos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pontosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_pontosMouseReleased(evt);
            }
        });
        getContentPane().add(btn_pontos);
        btn_pontos.setBounds(10, 270, 110, 70);

        btn_vendas.setText("Vendas");
        btn_vendas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_vendasMouseDragged(evt);
            }
        });
        btn_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vendasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vendasMouseReleased(evt);
            }
        });
        getContentPane().add(btn_vendas);
        btn_vendas.setBounds(10, 180, 110, 70);

        btn_funcionario.setText("Funcionário");
        btn_funcionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_funcionarioMouseDragged(evt);
            }
        });
        btn_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_funcionarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_funcionarioMouseReleased(evt);
            }
        });
        btn_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_funcionario);
        btn_funcionario.setBounds(10, 100, 110, 70);

        btn_cliente.setText("Cliente");
        btn_cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_clienteMouseDragged(evt);
            }
        });
        btn_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clienteMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_clienteMouseReleased(evt);
            }
        });
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cliente);
        btn_cliente.setBounds(10, 10, 110, 70);

        btn_produto.setText("Produto");
        btn_produto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_produtoMouseDragged(evt);
            }
        });
        btn_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_produtoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_produtoMouseReleased(evt);
            }
        });
        getContentPane().add(btn_produto);
        btn_produto.setBounds(140, 10, 110, 70);

        btn_login.setText("Login");
        btn_login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_loginMouseDragged(evt);
            }
        });
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_loginMouseReleased(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(140, 100, 110, 70);
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, 0, 0, 0);

        mnu_cliente.setText("Cliente");
        mnu_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_clienteMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_cliente);

        mnu_funcionario.setText("Funcionário");
        mnu_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_funcionarioMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_funcionario);

        mnu_vendas.setText("Vendas");
        mnu_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_vendasMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_vendas);

        mnu_pontos.setText("Pontos");
        mnu_pontos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_pontosMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_pontos);

        mnu_produto.setText("Produto");
        mnu_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_produtoMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_produto);

        mnu_login.setText("Login");
        mnu_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_loginMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_login);

        mnu_alterarFundo.setText("Plano de Fundo");
        mnu_alterarFundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_alterarFundoMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_alterarFundo);

        mnu_logout.setText("Log-Out");
        mnu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_logoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_logout);

        mnu_sair.setText("Sair");
        mnu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_sairMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnu_sair);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void btn_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_funcionarioActionPerformed

    private void btn_clienteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clienteMouseDragged
        inicioControler.arrastarBotao(this.btn_cliente, evt);
    }//GEN-LAST:event_btn_clienteMouseDragged

    private void btn_funcionarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_funcionarioMouseDragged
        inicioControler.arrastarBotao(this.btn_funcionario, evt);    }//GEN-LAST:event_btn_funcionarioMouseDragged

    private void btn_vendasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vendasMouseDragged
        inicioControler.arrastarBotao(this.btn_vendas, evt);    }//GEN-LAST:event_btn_vendasMouseDragged

    private void btn_pontosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pontosMouseDragged
        inicioControler.arrastarBotao(this.btn_pontos, evt);
    }//GEN-LAST:event_btn_pontosMouseDragged

    private void btn_produtoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produtoMouseDragged
        inicioControler.arrastarBotao(this.btn_produto, evt);
    }//GEN-LAST:event_btn_produtoMouseDragged

    private void btn_historicoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historicoMouseDragged
        inicioControler.arrastarBotao(this.btn_historico, evt);
    }//GEN-LAST:event_btn_historicoMouseDragged

    private void mnu_alterarFundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_alterarFundoMouseClicked
        inicioControler.mudarPlanoFundo(lbl_fundo);
    }//GEN-LAST:event_mnu_alterarFundoMouseClicked

    private void mnu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnu_sairMouseClicked

    private void btn_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clienteMouseClicked
        inicioControler.abrirCliente(this);
    }//GEN-LAST:event_btn_clienteMouseClicked

    private void btn_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_funcionarioMouseClicked
        inicioControler.abrirFuncionario(this);
    }//GEN-LAST:event_btn_funcionarioMouseClicked

    private void btn_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vendasMouseClicked
        inicioControler.abrirVenda(this);
    }//GEN-LAST:event_btn_vendasMouseClicked

    private void btn_pontosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pontosMouseClicked
        inicioControler.abrirPonto(this);
    }//GEN-LAST:event_btn_pontosMouseClicked

    private void btn_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produtoMouseClicked
        inicioControler.abrirProduto(this);
    }//GEN-LAST:event_btn_produtoMouseClicked

    private void btn_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historicoMouseClicked
        
        
    }//GEN-LAST:event_btn_historicoMouseClicked

    private void mnu_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_clienteMouseClicked
        inicioControler.abrirCliente(this);
    }//GEN-LAST:event_mnu_clienteMouseClicked

    private void mnu_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_funcionarioMouseClicked
        inicioControler.abrirFuncionario(this);
    }//GEN-LAST:event_mnu_funcionarioMouseClicked

    private void mnu_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_vendasMouseClicked
        inicioControler.abrirVenda(this);
    }//GEN-LAST:event_mnu_vendasMouseClicked

    private void mnu_pontosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_pontosMouseClicked
        inicioControler.abrirPonto(this);
    }//GEN-LAST:event_mnu_pontosMouseClicked

    private void mnu_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_produtoMouseClicked
        inicioControler.abrirProduto(this);
    }//GEN-LAST:event_mnu_produtoMouseClicked

    private void mnu_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_loginMouseClicked
        inicioControler.abrirLogin(this);
    }//GEN-LAST:event_mnu_loginMouseClicked

    private void mnu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_logoutMouseClicked
        inicioControler.logout(this);
    }//GEN-LAST:event_mnu_logoutMouseClicked

    private void btn_loginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseDragged
        inicioControler.arrastarBotao(this.btn_login, evt);
    }//GEN-LAST:event_btn_loginMouseDragged

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        inicioControler.abrirLogin(this);
    }//GEN-LAST:event_btn_loginMouseClicked

    
    
    
    private void btn_clienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clienteMouseReleased
        inicioControler.guardaPosicao();
    }//GEN-LAST:event_btn_clienteMouseReleased

    private void btn_funcionarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_funcionarioMouseReleased
        inicioControler.guardaPosicao();
        
    }//GEN-LAST:event_btn_funcionarioMouseReleased

    private void btn_vendasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vendasMouseReleased
        inicioControler.guardaPosicao();
    }//GEN-LAST:event_btn_vendasMouseReleased

    private void btn_pontosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pontosMouseReleased
        inicioControler.guardaPosicao();
    }//GEN-LAST:event_btn_pontosMouseReleased

    private void btn_produtoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produtoMouseReleased
        inicioControler.guardaPosicao();
    }//GEN-LAST:event_btn_produtoMouseReleased

    private void btn_loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseReleased
        inicioControler.guardaPosicao();
    }//GEN-LAST:event_btn_loginMouseReleased

    private void btn_historicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historicoMouseReleased
        inicioControler.guardaPosicao();
    }//GEN-LAST:event_btn_historicoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_funcionario;
    private javax.swing.JButton btn_historico;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_pontos;
    private javax.swing.JButton btn_produto;
    private javax.swing.JButton btn_vendas;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JMenu mnu_alterarFundo;
    private javax.swing.JMenu mnu_cliente;
    private javax.swing.JMenu mnu_funcionario;
    private javax.swing.JMenu mnu_login;
    private javax.swing.JMenu mnu_logout;
    private javax.swing.JMenu mnu_pontos;
    private javax.swing.JMenu mnu_produto;
    private javax.swing.JMenu mnu_sair;
    private javax.swing.JMenu mnu_vendas;
    // End of variables declaration//GEN-END:variables

    private void inseriMapa() {
        this.mapaComponentes = new HashMap<>();
        
        this.mapaComponentes.put("tela", this);
        this.mapaComponentes.put("lbl_fundo", this.lbl_fundo);
        
        this.mapaComponentes.put("btn_cliente", this.btn_cliente);
        this.mapaComponentes.put("btn_funcionario", this.btn_funcionario);
        this.mapaComponentes.put("btn_login", this.btn_login);
        this.mapaComponentes.put("btn_pontos", this.btn_pontos);
        this.mapaComponentes.put("btn_produto", this.btn_produto);
        this.mapaComponentes.put("btn_vendas", this.btn_vendas);
        this.mapaComponentes.put("btn_historico", this.btn_historico);
    }


}
