-- MySQL Script generated by MySQL Workbench
-- Sat Apr 14 10:57:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema intelbras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema intelbras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `intelbras` DEFAULT CHARACTER SET utf8 ;
USE `intelbras` ;

-- -----------------------------------------------------
-- Table `intelbras`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(80) NULL DEFAULT NULL,
  `cpfCliente` VARCHAR(15) NULL DEFAULT NULL,
  `rgCliente` VARCHAR(14) NULL DEFAULT NULL,
  `sexoCliente` VARCHAR(10) NULL DEFAULT NULL,
  `dataNascCliente` VARCHAR(20) NULL DEFAULT NULL,
  `bairroCliente` VARCHAR(45) NULL DEFAULT NULL,
  `cepCliente` VARCHAR(10) NULL DEFAULT NULL,
  `telefoneCliente` VARCHAR(16) NULL DEFAULT NULL,
  `enderecoCliente` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intelbras`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(80) NULL DEFAULT NULL,
  `cpfFuncionario` VARCHAR(15) NULL DEFAULT NULL,
  `rgFuncionario` VARCHAR(14) NULL DEFAULT NULL,
  `enderecoFuncionario` VARCHAR(80) NULL DEFAULT NULL,
  `cepFuncionario` VARCHAR(10) NULL DEFAULT NULL,
  `bairroFuncionario` VARCHAR(45) NULL DEFAULT NULL,
  `telefoneFuncionario` VARCHAR(16) NULL DEFAULT NULL,
  `sexoFuncionario` VARCHAR(10) NULL DEFAULT NULL,
  `salarioFuncionario` DOUBLE NULL DEFAULT NULL,
  `setorFuncionario` VARCHAR(45) NULL DEFAULT NULL,
  `comissaoFuncionario` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intelbras`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`login` (
  `idLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeLogin` VARCHAR(45) NOT NULL,
  `emailLogin` VARCHAR(45) NULL DEFAULT NULL,
  `senhaLogin` VARCHAR(45) NOT NULL,
  `Funcionario_idFuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Login_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `intelbras`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intelbras`.`ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`ponto` (
  `idPontos` INT(11) NOT NULL AUTO_INCREMENT,
  `dataPonto` VARCHAR(20) NOT NULL,
  `setorPonto` VARCHAR(45) NULL DEFAULT NULL,
  `Funcionario_idFuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idPontos`),
  INDEX `fk_Ponto_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Ponto_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `intelbras`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intelbras`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`produto` (
  `idProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `descricaoProduto` MEDIUMTEXT NULL DEFAULT NULL,
  `marcaProduto` VARCHAR(45) NULL DEFAULT NULL,
  `valorProduto` FLOAT UNSIGNED NULL DEFAULT NULL,
  `modeloProduto` VARCHAR(45) NULL DEFAULT NULL,
  `obsProduto` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intelbras`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`vendas` (
  `idVendas` INT(11) NOT NULL AUTO_INCREMENT,
  `dataVenda` VARCHAR(20) NULL DEFAULT NULL,
  `valorTotalVenda` FLOAT NULL DEFAULT NULL,
  `obsVenda` MEDIUMTEXT NULL DEFAULT NULL,
  `Cliente_idCliente` INT(11) NOT NULL,
  `Funcionario_idFuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `fk_Vendas_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Vendas_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Vendas_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `intelbras`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `intelbras`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `intelbras`.`vendas_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intelbras`.`vendas_has_produto` (
  `Vendas_idVendas` INT(11) NOT NULL,
  `Produto_idProduto` INT(11) NOT NULL,
  PRIMARY KEY (`Vendas_idVendas`, `Produto_idProduto`),
  INDEX `fk_Vendas_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Vendas_has_Produto_Vendas_idx` (`Vendas_idVendas` ASC),
  CONSTRAINT `fk_Vendas_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `intelbras`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_has_Produto_Vendas`
    FOREIGN KEY (`Vendas_idVendas`)
    REFERENCES `intelbras`.`vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
