-- MySQL Script generated by MySQL Workbench
-- Thu Mar  8 23:50:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Intelbras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Intelbras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Intelbras` DEFAULT CHARACTER SET utf8 ;
USE `Intelbras` ;

-- -----------------------------------------------------
-- Table `Intelbras`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(80) NULL,
  `cpfFuncionario` VARCHAR(15) NULL,
  `rgFuncionario` VARCHAR(14) NULL,
  `enderecoFuncionario` VARCHAR(80) NULL,
  `cepFuncionario` VARCHAR(10) NULL,
  `bairroFuncionario` VARCHAR(45) NULL,
  `telefoneFuncionario` VARCHAR(16) NULL,
  `sexoFuncionario` VARCHAR(10) NULL,
  `salarioFuncionario` DOUBLE NULL,
  `setorFuncionario` VARCHAR(45) NULL,
  `comissaoFuncionario` FLOAT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intelbras`.`Ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Ponto` (
  `idPontos` INT NOT NULL AUTO_INCREMENT,
  `dataPonto` DATE NOT NULL,
  `setorPonto` VARCHAR(45) NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idPontos`),
  INDEX `fk_Ponto_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Ponto_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `Intelbras`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intelbras`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `nomeLogin` VARCHAR(45) NOT NULL,
  `emailLogin` VARCHAR(45) NULL,
  `senhaLogin` VARCHAR(45) NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Login_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `Intelbras`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intelbras`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(80) NULL,
  `cpfCliente` VARCHAR(15) NULL,
  `rgCliente` VARCHAR(14) NULL,
  `sexoCliente` VARCHAR(10) NULL,
  `dataNascCliente` DATE NULL,
  `bairroCliente` VARCHAR(45) NULL,
  `cepCliente` VARCHAR(10) NULL,
  `telefoneCliente` VARCHAR(16) NULL,
  `enderecoCliente` VARCHAR(80) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intelbras`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NULL,
  `valorTotalVenda` FLOAT NULL,
  `obsVenda` MEDIUMTEXT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `fk_Vendas_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Vendas_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Vendas_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Intelbras`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `Intelbras`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intelbras`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descricaoProduto` MEDIUMTEXT NULL,
  `marcaProduto` VARCHAR(45) NULL,
  `valorProduto` FLOAT UNSIGNED NULL,
  `modeloProduto` VARCHAR(45) NULL,
  `obsProduto` MEDIUMTEXT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Intelbras`.`Vendas_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Intelbras`.`Vendas_has_Produto` (
  `Vendas_idVendas` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Vendas_idVendas`, `Produto_idProduto`),
  INDEX `fk_Vendas_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Vendas_has_Produto_Vendas_idx` (`Vendas_idVendas` ASC),
  CONSTRAINT `fk_Vendas_has_Produto_Vendas`
    FOREIGN KEY (`Vendas_idVendas`)
    REFERENCES `Intelbras`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `Intelbras`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
